### ISSUE TITLE
MIT License

### ISSUE THREAD

**Issue by saraedum** [flatsurf/cppyythonizations#1]
@videlec I will copy some of Python/cppyy helpers from the other projects here. I want to use MIT license for this project as that is cppyy's license and I guess it's nice to fit into its eco-system by using a matching license.

Are you ok with relicensing the bits that I copy over under MIT? (Not sure you actually authored any of it, but it's easier to just ask than having to check every single line of code :)

**Comment by videlec** [comment]
fine with me.
